apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: test-namespace
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: jhenekova/exam
          ports:
            - containerPort: 80