apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: test-namespace
spec:
  type: NodePort
  clusterIP: 10.102.102.21
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200